//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class biletler
    {
        public int bilet_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> koltuk_id { get; set; }
        public Nullable<System.DateTime> satin_almaTarihi { get; set; }
        public Nullable<decimal> fiyat { get; set; }

        public int  koltuk_no {  get; set; }
        public string cinsiyet { get; set; }
        public string tc {  get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public bool isEmpty { get; set; }

        public string kat { get; set; }
        public int seyahat_id { get; set; }
        public int sefer_id { get; set; }

    }
}
