//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class koltuklar
    {
        public int koltuk_id { get; set; }
        public Nullable<int> seyahat_id { get; set; }
        public Nullable<int> koltuk_numarasi { get; set; }
        public Nullable<bool> isEmpty { get; set; }
		public string kat { get; set; }
	}
}
