//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otobusbiletDBEntities : DbContext
    {
        public otobusbiletDBEntities()
            : base("name=otobusbiletDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<biletler> biletler { get; set; }
        public virtual DbSet<koltuklar> koltuklar { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<otobusler> otobusler { get; set; }
        public virtual DbSet<seferler> seferler { get; set; }
        public virtual DbSet<sifre_sifirlama> sifre_sifirlama { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
