//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class otobusler
    {
        public int otobus_id { get; set; }
        public string plaka { get; set; }
        public Nullable<int> koltuk_sayisi { get; set; }
        public string firma_adi { get; set; }
        public string otobus_resim { get; set; }
        public Nullable<int> peron_no { get; set; }
    }
}
