//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class seferler
    {
        public int seyahat_id { get; set; }
        public string kalkis { get; set; }
        public string varis { get; set; }
        public Nullable<System.DateTime> kalkis_zamani { get; set; }
        public Nullable<decimal> bilet_fiyat { get; set; }
        public Nullable<int> otobus_id { get; set; }
        public Nullable<int> otobus_type { get; set; }
    }
}
