//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biletalproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class sifre_sifirlama
    {
        public int sifre_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public string sifirla { get; set; }
        public Nullable<System.DateTime> son_kullanmaTarihi { get; set; }
        public Nullable<bool> kullanilan { get; set; }
    }
}
